### ISSUE TITLE
CloudFormation: Public S3 zip not accessible

### ISSUE THREAD

**Issue by hazarkarabay** [binxio/aws-cloudwatch-log-minder#27]
Hi, I just want to inform that the link `https://binxio-public-eu-central-1.s3.eu-central-1.amazonaws.com/lambdas/aws-cloudwatch-log-minder-0.4.1.zip` is currently not accessible so CloudFormation stack creation fails.

Thank you.

**Comment by mvanholsteijn** [comment]
Hi @hazarkarabay , sorry about that. it is available now in all the regions.
