### ISSUE TITLE
Please add `--region` and `--profile` options

### ISSUE THREAD

**Issue by atombrenner** [binxio/aws-cloudwatch-log-minder#4]
It would be nice if this utility could support the `--region` and `--profile` options like the aws-cli does.
This would enable us to use this tool in an environment with many accounts, regions and profiles.

E.g. I have several profiles for several accounts, and each account has one profile for readonly and admin access.

`cwlog-minder --dry-run delete-empty-log-streams --profile my-admin` would allow me to use this tool much more easily on the command line.

**Comment by mvanholsteijn** [comment]
The quick and easy way is to type:

```
AWS_REGION=eu-central-1 AWS_PROFILE=my-admin cwlog-minder --dry-run delete-empty-log-streams 
```
