### ISSUE TITLE
No output for set-log-retention dry-run 

### ISSUE THREAD

**Issue by otanner** [binxio/aws-cloudwatch-log-minder#5]
Hi,

I am not receiving any output when running `set-log-retention` in `dry-run` mode. I wasn't brave enough to try it without the `dry-run` flag. I also have a lot of log groups with no retention set.

My guess is that this is related to https://stackoverflow.com/questions/43109355/logging-setlevel-is-being-ignored and pull request https://github.com/binxio/aws-cloudwatch-log-minder/pull/1 would fix this.

**Comment by JCotton1123** [comment]
I can confirm this is still an issue. I was able to resolve it via the following patch:

```diff
diff --git a/src/aws_cloudwatch_log_minder/logger.py b/src/aws_cloudwatch_log_minder/logger.py
index 47e3fdd..cf165b7 100644
--- a/src/aws_cloudwatch_log_minder/logger.py
+++ b/src/aws_cloudwatch_log_minder/logger.py
@@ -1,5 +1,5 @@
 import os
 import logging

-logging.basicConfig(format="%(levelname)s: %(message)s", level=os.getenv("LOG_LEVEL", "INFO"))
 log = logging.getLogger()
+log.setLevel(os.getenv("LOG_LEVEL", "INFO"))
```
