### ISSUE TITLE
The storedBytes  for the stream used in delete_empty_log_streams.py is deprecated 

### ISSUE THREAD

**Issue by sheridansmall** [binxio/aws-cloudwatch-log-minder#8]
From https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/logs.html#CloudWatchLogs.Client.describe_log_streams

> storedBytes (integer) --
> The number of bytes stored.
> IMPORTANT: On June 17, 2019, this parameter was deprecated for log streams, and is always reported as zero. This change applies only to log streams. The storedBytes parameter for log groups is not affected.

The code uses this parameter in delete_empty_log_streams.py.
I am observing some storedBytes to have a value other than zero when the stream is empty.

**Comment by mvanholsteijn** [comment]
@sheridansmall thank you for notifying me..
